export const SKILL_DOMAINS: Record<string, string[]> = {
  "Frontend Development": [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "Svelte",
    "Tailwind CSS",
    "Redux",
    "Webpack",
    "Vite",
    "Responsive Design",
    "Web Accessibility",
    "Jest",
    "Cypress",
    "GraphQL",
  ],
  "Backend Development": [
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "FastAPI",
    "Java",
    "Spring Boot",
    "C#",
    ".NET",
    "Go",
    "Ruby on Rails",
    "PHP",
    "Laravel",
    "REST APIs",
    "GraphQL",
    "Microservices",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "RabbitMQ",
    "Kafka",
  ],
  "Full Stack Development": [
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "PostgreSQL",
    "MongoDB",
    "REST APIs",
    "GraphQL",
    "Prisma",
    "tRPC",
    "Docker",
    "AWS",
    "CI/CD",
    "Git",
  ],
  "Mobile Development": [
    "React Native",
    "Flutter",
    "Swift",
    "SwiftUI",
    "Kotlin",
    "Jetpack Compose",
    "Java (Android)",
    "Objective-C",
    "Dart",
    "Mobile UI/UX",
    "Push Notifications",
    "App Store Deployment",
    "Firebase",
    "SQLite",
  ],
  "DevOps & Cloud": [
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "CI/CD",
    "Linux",
    "Bash Scripting",
    "Prometheus",
    "Grafana",
    "Nginx",
    "Serverless",
    "Infrastructure as Code",
  ],
  "Data Science & ML": [
    "Python",
    "R",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "Statistics",
    "Data Visualization",
    "Matplotlib",
    "Jupyter",
    "SQL",
    "MLOps",
    "LLMs",
    "Prompt Engineering",
  ],
  "Data Engineering": [
    "SQL",
    "Python",
    "Apache Spark",
    "Apache Airflow",
    "Kafka",
    "ETL Pipelines",
    "Data Warehousing",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "dbt",
    "Hadoop",
    "Data Modeling",
    "PostgreSQL",
    "NoSQL",
  ],
  "QA & Testing": [
    "Manual Testing",
    "Automation Testing",
    "Selenium",
    "Playwright",
    "Cypress",
    "Jest",
    "API Testing",
    "Postman",
    "Performance Testing",
    "JMeter",
    "Test Planning",
    "Bug Tracking",
    "Regression Testing",
    "TestRail",
  ],
  "Cybersecurity": [
    "Network Security",
    "Penetration Testing",
    "Ethical Hacking",
    "SIEM",
    "Vulnerability Assessment",
    "OWASP",
    "Cryptography",
    "Incident Response",
    "Firewall Management",
    "Security Auditing",
    "Kali Linux",
    "Burp Suite",
    "SOC Operations",
    "Compliance (ISO 27001, SOC 2)",
  ],
  "UI/UX Design": [
    "Figma",
    "Adobe XD",
    "Sketch",
    "Wireframing",
    "Prototyping",
    "User Research",
    "Usability Testing",
    "Design Systems",
    "Interaction Design",
    "Visual Design",
    "Information Architecture",
    "Accessibility Design",
  ],
  "Product Management": [
    "Product Strategy",
    "Roadmapping",
    "Agile",
    "Scrum",
    "User Stories",
    "Market Research",
    "A/B Testing",
    "Analytics",
    "Stakeholder Management",
    "JIRA",
    "Product Discovery",
    "Go-to-Market Strategy",
    "OKRs",
  ],
  "Data Analytics & BI": [
    "SQL",
    "Excel",
    "Power BI",
    "Tableau",
    "Looker",
    "Python",
    "Data Visualization",
    "Statistical Analysis",
    "Google Analytics",
    "Dashboard Design",
    "Business Intelligence",
    "Reporting",
  ],
};

export const DOMAIN_NAMES = Object.keys(SKILL_DOMAINS);
